// A file for storing action types used throughout out app.

export default {
  APP_LOADED: 'APP_LOADED',
  ASYNC_START: 'ASYNC_START',
  GET_DATA: 'GET_DATA',
  SEARCH_VALUE_CHANGE: 'SEARCH_VALUE_CHANGE',
  CLEAR_RESULTS: 'CLEAR_RESULTS',
  UNLOAD_PAGE: 'UNLOAD_PAGE',
  RESULTS_PAGE: 'RESULTS_PAGE',
  SEARCH_PANEL_DROP_DOWN: 'SEARCH_PANEL_DROP_DOWN',
}
