// A file for storing action types used throughout out app.

export default {
  ASYNC_START: 'ASYNC_START',
  GET_DATA: 'GET_DATA',
  SEARCH_VALUE_CHANGE: 'SEARCH_VALUE_CHANGE',
  CLEAR_DATA: 'CLEAR_DATA',
  RESULTS_LIST_PAGE_FORWARDS: 'RESULTS_LIST_PAGE_FORWARDS',
  RESULTS_LIST_PAGE_BACKWARDS: 'RESULTS_LIST_PAGE_BACKWARDS',
  MOVE_TO_RESULTS_PANEL: 'MOVE_TO_RESULTS_PANEL',
  CLEAR_ALL: 'CLEAR_ALL',
}
